services:
  weather_api:
    build:
      context: ./subscription-service
      dockerfile: Dockerfile.dev
    container_name: express_weather_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./subscription-service/.env
    depends_on:
      - postgres_db
    volumes:
      - ./subscription-service/src:/app/src

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile.dev
    container_name: weather_scheduler
    environment:
      - NODE_ENV=development
    env_file:
      - ./scheduler/.env
    depends_on:
      - weather_api
      - postgres_db

  postgres_db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: weather-postgres-dev
    ports:
      - "5432:5432"
    env_file:
      - ./subscription-service/.env
    environment:
      - POSTGRES_INITDB_ARGS='--locale=en_US.UTF-8'
