services:
  weather_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express_weather_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - postgres_db
    volumes:
      - ./src:/app/src

  postgres_db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: weather-postgres-dev
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_INITDB_ARGS='--locale=en_US.UTF-8'
