FROM node:22

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
EXPOSE 3000

RUN chmod +x /app/scripts/docker-entrypoint.sh

ENTRYPOINT [ "/app/scripts/docker-entrypoint.sh" ]